version: "3"

services:
    app:
        image: node
        container_name: app-container
        working_dir: /usr/src/service
        volumes:
            - ./app/intend-pwa:/usr/src/service
        ports:
            - 80:8080
            - 1235:1235
        command: bash -c "npm install && npm run serve"
    api:
        image: php:fpm
        container_name: api-container
        working_dir: /var/www
        volumes:
            - ./api:/var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=db"
            - "DB_CONNECTION=mysql"
        command: bash -c "docker-php-ext-install pdo pdo_mysql && php-fpm"
    srv:
        image: nginx
        container_name: srv-container
        ports:
            - 8080:8080
        volumes:
            - ./api:/var/www
            - ./conf.d:/etc/nginx/conf.d
    db:
        image: mysql:5.7
        container_name: db-container
        ports:
            - 3306:3306
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'admin'

volumes:
    dbdata:
